package layout.panels;

import java.util.Vector;

import scr.dao.CondicionDao;
import scr.dao.SectoresDao;
import scr.entidades.Condicion;
import scr.entidades.Sector;

/**
 *
 * @author  ZIGGY STARDUST
 */
public class JPanelAltaCondicion extends javax.swing.JPanel {
    
	private static final long serialVersionUID = 2283849863122519093L;
	
	CondicionDao condicionDao = new CondicionDao();
	SectoresDao sectorDao = new SectoresDao();

	/** Creates new form JPanelAltaCondicion */
    public JPanelAltaCondicion() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Código Generado  ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLTitulo = new javax.swing.JLabel();
        jLSector = new javax.swing.JLabel();
        jLDescripcion = new javax.swing.JLabel();
        jLComparador = new javax.swing.JLabel();
        jLTipo = new javax.swing.JLabel();
        jCBSector = new javax.swing.JComboBox();
        jTFDescripcion = new javax.swing.JTextField();
        jCBComparador = new javax.swing.JComboBox();
        jCBTipo = new javax.swing.JComboBox();
        jBAceptar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();

        jLTitulo.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLTitulo.setText("ALTA CONDICI\u00d3N");

        jLSector.setText("Sector");

        jLDescripcion.setText("Descripci\u00f3n");

        jLComparador.setText("Comparador");

        jLTipo.setText("Tipo");

        //jCBSector.setModel(new javax.swing.DefaultComboBoxModel(sectorDao.getSectores().toArray()));
        Vector<Sector>vec = new Vector<Sector>();
        Sector sector = new Sector();
        sector.setIdsector(1);
        sector.setDescripcion("sector 1");
        vec.add(sector);
        sector = new Sector();
        sector.setIdsector(2);
        sector.setDescripcion("sector 2");
        vec.add(sector);
        jCBSector.setModel(new javax.swing.DefaultComboBoxModel(vec));

        jCBComparador.setModel(new javax.swing.DefaultComboBoxModel(new String[] { ">=", "<=", "=" }));

        jCBTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Horaria", "Numerica"}));

        jBAceptar.setText("Aceptar");
        jBAceptar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBAceptarKeyPressed(evt);
            }
        });
        jBAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBAceptarMouseClicked(evt);
            }
        });

        jBCancelar.setText("Cancelar");
        jBCancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBCancelarKeyPressed(evt);
            }
        });
        jBCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBCancelarMouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(91, 91, 91)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jBAceptar)
                        .add(39, 39, 39)
                        .add(jBCancelar)
                        .addContainerGap())
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLDescripcion)
                                    .add(jLSector))
                                .add(46, 46, 46)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(jTFDescripcion)
                                    .add(jCBSector, 0, 129, Short.MAX_VALUE)))
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLComparador)
                                    .add(jLTipo))
                                .add(41, 41, 41)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, jCBTipo, 0, 129, Short.MAX_VALUE)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, jCBComparador, 0, 129, Short.MAX_VALUE))))
                        .add(80, 80, 80))))
            .add(layout.createSequentialGroup()
                .add(149, 149, 149)
                .add(jLTitulo)
                .addContainerGap(157, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(25, 25, 25)
                .add(jLTitulo)
                .add(41, 41, 41)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLSector)
                    .add(jCBSector, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLDescripcion)
                    .add(jTFDescripcion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLComparador)
                    .add(jCBComparador, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLTipo)
                    .add(jCBTipo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(33, 33, 33)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jBAceptar)
                    .add(jBCancelar))
                .addContainerGap(60, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBCancelarMouseClicked
    	this.setVisible(false);
    }//GEN-LAST:event_jBCancelarMouseClicked

    private void jBCancelarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBCancelarKeyPressed
    	this.setVisible(false);
    }//GEN-LAST:event_jBCancelarKeyPressed

    private void jBAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBAceptarMouseClicked
    	Condicion condicion = new Condicion();
    	condicion.setDescripcion(this.jTFDescripcion.getText());
    	Sector sector = (Sector) this.jCBSector.getSelectedItem();
    	condicion.setIdSector(sector.getIdsector());
    	/**
    	 * TODO: ver o que devuelve este selected index
    	 */
    	condicion.setComparador(this.jCBComparador.getSelectedIndex());
   		condicion.setDiscriminador(this.jCBTipo.getSelectedIndex());
   		/**
   		 * TODO: agregar campo inicio al formulario.> inicio o fin
   		 */
   		condicion.setInicio(1);
   		condicionDao.insertCondicion(condicion);
    	this.setVisible(false);
    }//GEN-LAST:event_jBAceptarMouseClicked

    private void jBAceptarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBAceptarKeyPressed
    	this.jBAceptarMouseClicked(null);
    }//GEN-LAST:event_jBAceptarKeyPressed
    
    
    // Declaración de varibales -no modificar//GEN-BEGIN:variables
    private javax.swing.JButton jBAceptar;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JComboBox jCBComparador;
    private javax.swing.JComboBox jCBSector;
    private javax.swing.JComboBox jCBTipo;
    private javax.swing.JLabel jLComparador;
    private javax.swing.JLabel jLDescripcion;
    private javax.swing.JLabel jLSector;
    private javax.swing.JLabel jLTipo;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JTextField jTFDescripcion;
    // Fin de declaración de variables//GEN-END:variables
    
}
