package layout.panels;

/**
 *
 * @author  ZIGGY STARDUST
 */
public class JPanelAltaCampo extends javax.swing.JPanel {
    
	private static final long serialVersionUID = 4040532380619581418L;
	
	/** Creates new form JPanelAltaProductor */
    public JPanelAltaCampo() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLNombre = new javax.swing.JLabel();
        jLTitulo = new javax.swing.JLabel();
        jBAceptar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jTFNombre = new javax.swing.JTextField();
        jLProductor = new javax.swing.JLabel();
        jCBProductor = new javax.swing.JComboBox();
        jLDomicilio = new javax.swing.JLabel();
        jLDomicilioString = new javax.swing.JLabel();

        jLNombre.setText("Nombre Campo");

        jLTitulo.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLTitulo.setText("ALTA CAMPO");

        jBAceptar.setText("Aceptar");
        jBAceptar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBAceptarKeyPressed(evt);
            }
        });
        jBAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBAceptarMouseClicked(evt);
            }
        });

        jBCancelar.setText("Cancelar");
        jBCancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBCancelarKeyPressed(evt);
            }
        });
        jBCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBCancelarMouseClicked(evt);
            }
        });

        jLProductor.setText("Productor");

        jCBProductor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Artículo 1", "Artículo 2", "Artículo 3", "Artículo 4" }));
        jCBProductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBProductorActionPerformed(evt);
            }
        });

        jLDomicilio.setText("Domicilio");

        jLDomicilioString.setText("Alicia Moreau de Justo 226");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(89, 89, 89)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(65, 65, 65)
                        .add(jBAceptar)
                        .add(35, 35, 35)
                        .add(jBCancelar))
                    .add(layout.createSequentialGroup()
                        .add(99, 99, 99)
                        .add(jLTitulo)))
                .addContainerGap(189, Short.MAX_VALUE))
            .add(layout.createSequentialGroup()
                .add(85, 85, 85)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLNombre)
                        .addContainerGap())
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLProductor)
                            .add(jLDomicilio))
                        .add(74, 74, 74)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLDomicilioString)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(jTFNombre, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                .add(jCBProductor, 0, 171, Short.MAX_VALUE)))
                        .add(151, 151, 151))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLTitulo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLProductor)
                    .add(jCBProductor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(26, 26, 26)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLNombre)
                    .add(jTFNombre, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(30, 30, 30)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLDomicilio)
                    .add(jLDomicilioString))
                .add(62, 62, 62)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jBCancelar)
                    .add(jBAceptar))
                .add(34, 34, 34))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBCancelarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBCancelarKeyPressed
// TODO: Agrege su codigo aqui:
    }//GEN-LAST:event_jBCancelarKeyPressed

    private void jBCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBCancelarMouseClicked
// TODO: Agrege su codigo aqui:
    }//GEN-LAST:event_jBCancelarMouseClicked

    private void jBAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBAceptarMouseClicked
// TODO: Agrege su codigo aqui:
    }//GEN-LAST:event_jBAceptarMouseClicked

    private void jBAceptarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBAceptarKeyPressed
// TODO: Agrege su codigo aqui:
    }//GEN-LAST:event_jBAceptarKeyPressed

    private void jCBProductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBProductorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBProductorActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAceptar;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JComboBox jCBProductor;
    private javax.swing.JLabel jLDomicilio;
    private javax.swing.JLabel jLDomicilioString;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLProductor;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JTextField jTFNombre;
    // End of variables declaration//GEN-END:variables
    
}
